import { swApi } from '@/api/sw-api';
import { StarshipsGetRequestParameters, StarshipsGetResponse } from '@/api/starships/starships-model';
import { API_ENDPOINTS } from '@/api/model';

// Extending the swApi with custom endpoints for fetching starship data
export const starshipsApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllStarships: build.query<StarshipsGetResponse, StarshipsGetRequestParameters>({
			query: ({ page }) => ({
				url: API_ENDPOINTS.STARSHIPS,
				params: { page },
			}),
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllStarshipsQuery } = starshipsApi;
