import { swApi } from '@/api/sw-api';
import { Pilot, PilotsGetRequestParameters, PilotsGetResponse } from '@/api/pilots/pilots-model';
import { API_ENDPOINTS } from '@/api/model';

// Extending the swApi with custom endpoints for fetching pilot data
export const pilotsApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllPilots: build.query<PilotsGetResponse, PilotsGetRequestParameters>({
			query: ({ page }) => ({
				url: API_ENDPOINTS.PILOTS,
				params: { page },
			}),
		}),
		getPilotById: build.query<Pilot, string>({
			query: (pilotId) => ({
				url: `${API_ENDPOINTS.PILOTS}/${pilotId}`,
			}),
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllPilotsQuery, useGetPilotByIdQuery } = pilotsApi;
