import { Photo, Photos, PhotosGetRequestParameters, PhotosGetResponse } from '@/api/photos/photos-model';
import unsplashApi from '@/api/unsplash-api';
import { swApi } from '@/api/sw-api';

// Utility function to serialize photo data, extracting the 'regular' image URLs
const serializePhotos = (results: Photos): Array<string> => {
	return results.map((result: Photo) => result.urls.regular);
};

// Extending the swApi with custom endpoints for fetching photo data
export const photosApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllPhotos: build.query<Array<string>, PhotosGetRequestParameters>({
			queryFn: async ({ query, page, orientation, perPage }) => {
				const response = (await unsplashApi.search.getPhotos({ query, page, orientation, perPage, plus: 'mixed' })) as PhotosGetResponse;
				return { data: serializePhotos(response.response?.results || []) };
			},
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllPhotosQuery } = photosApi;
