import { swApi } from '@/api/sw-api';
import { FilmsGetRequestParameters, FilmsGetResponse } from '@/api/films/films-model';
import { API_ENDPOINTS } from '@/api/model';

// Extending the swApi with custom endpoints for fetching film data
export const filmsApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllFilms: build.query<FilmsGetResponse, FilmsGetRequestParameters>({
			query: ({ page }) => ({
				url: API_ENDPOINTS.FILMS,
				params: { page },
			}),
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllFilmsQuery } = filmsApi;
