import { swApi } from '@/api/sw-api';
import { PlanetsGetRequestParameters, PlanetsGetResponse } from '@/api/planets/planets-model';
import { API_ENDPOINTS } from '@/api/model';

// Extending the swApi with custom endpoints for fetching planet data
export const planetsApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllPlanets: build.query<PlanetsGetResponse, PlanetsGetRequestParameters>({
			query: ({ page }) => ({
				url: API_ENDPOINTS.PLANETS,
				params: { page },
			}),
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllPlanetsQuery } = planetsApi;
