import { swApi } from '@/api/sw-api';
import { VehiclesGetRequestParameters, VehiclesGetResponse } from '@/api/vehicles/vehicles-model';
import { API_ENDPOINTS } from '@/api/model';

// Extending the swApi with custom endpoints for fetching vehicle data
export const vehiclesApi = swApi.injectEndpoints({
	endpoints: (build) => ({
		getAllVehicles: build.query<VehiclesGetResponse, VehiclesGetRequestParameters>({
			query: ({ page }) => ({
				url: API_ENDPOINTS.VEHICLES,
				params: { page },
			}),
		}),
	}),
});

// Exporting the custom hook generated by Redux Toolkit Query for use in components
export const { useGetAllVehiclesQuery } = vehiclesApi;
